[package]
name = "win_lib_loader"
version = "0.1.0"
edition = "2021"
authors = ["Nareshkumar Rao"]

[dependencies]
win_lib_loader_proc = { path = "./win_lib_loader_proc", version = "*" }

[dependencies.winapi]
version = "0.3.9"
features = ["minwindef", "libloaderapi"]
