[package]
name = "win_lib_loader_proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.82", features = ["full"] }
quote = "1.0.37"
proc-macro2 = "1.0.89"
